//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBM_14Mar25_Day2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IBM14Mar25CWFDbEntities : DbContext
    {
        public IBM14Mar25CWFDbEntities()
            : base("name=IBM14Mar25CWFDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
    
        public virtual int GetFoodItemNameByID(Nullable<int> fooditmID, ObjectParameter foodName)
        {
            var fooditmIDParameter = fooditmID.HasValue ?
                new ObjectParameter("fooditmID", fooditmID) :
                new ObjectParameter("fooditmID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetFoodItemNameByID", fooditmIDParameter, foodName);
        }
    
        public virtual ObjectResult<GetFoodItems_Result> GetFoodItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFoodItems_Result>("GetFoodItems");
        }
    }
}
